### PR TITLE
Implementing nightly build only tests mechanism

### PR DESCRIPTION
**Pull request by hukoyu**
With this PR we can mark any test (long running ones for example) as nightly build only 
by adding them to file .azure-pipelines/other/nighlty_run_only_tests.txt

If SGXLKL_NIGHTLY_RUN  environment variable is NOT defined, the tests in this file will be skipped. 
These tests will run only if SGXLKL_NIGHTLY_RUN env variable is defined.

### CODE REVIEW

**Comment by hukoyu** [comment]
Verified that PR is working as expected.
https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1286&view=results 
ml/openvino test is skipped since SGXLKL_NIGHTLY_RUN is not set for sgx-lkl pipeline

**Comment by hukoyu** [comment]
cc @paulcallen @jxyang @letmaik @wintersteiger

**Comment by letmaik** [comment]
Can you post a link to a manually scheduled nightly CI run so we can verify it works?

**Review by wintersteiger — APPROVED** [review]
LGTM, thanks!

**Comment by wintersteiger** [comment]
CI build failed because of an untracked dependency in the new config code, fix is here: https://github.com/lsds/sgx-lkl/pull/621

**Comment by hukoyu** [comment]
> Can you post a link to a manually scheduled nightly CI run so we can verify it works?

@letmaik I tried nightly build with this PR and it didn't like defining SGXLKL_NIGHLTY_BUILD variable in variables: section. Trying to figure out defining a new variable in extending pipeline yaml file.

**Comment by hukoyu** [comment]
Dupe of https://github.com/lsds/sgx-lkl/pull/623

**Pull request closed without merging**
