### PR TITLE
Remove unneeded init_clock_res

### LINKED ISSUE #816: Dead code in sgx-lkl-musl
We have several functions that were work-arounds for missing features that are now fixed.  These have complicated some of the code cleanup, as seen in #815, where we're adding code to support these hacks.  We should remove them and simplify the associated code:

- [ ] `init_sysconf` should be obsolete now that we're intercepting the sysconf system call.
- [ ] `init_clock_res` should be obsolete now that LKL is managing the clocks.

@SeanTAllen, you've touched some code related to both of these, I think.  Can you take a look once #815 has landed?

### PR DESCRIPTION
**Pull request by SeanTAllen**
Closes #816

### CODE REVIEW

**Comment by SeanTAllen** [comment]
sgx-lkl-musl review is here:

https://github.com/lsds/sgx-lkl-musl/pull/40

**Comment by prp** [comment]
Shouldn't this also remove the associated enclave_config parameter?

**Comment by SeanTAllen** [comment]
@wintersteiger Should I remove the enclave_config parameter? I think you said you would do after this was done.

Let me know.

**Comment by wintersteiger** [comment]
@SeanTAllen sure, go ahead and remove them if you like. There are a couple of places in the launcher and the config parser that should be removed but the compiler might not throw errors. I'm happy to take another look later or after this is merged.

**Review by davidchisnall — APPROVED** [review]

**Review by wintersteiger — APPROVED** [review]
LGTM!

**Comment by SeanTAllen** [comment]
@wintersteiger I removed as much as I thought needed to go and it compiles now. I'm not sure if it will pass tests or not. Can you take a look to see if I missed anything?

**Comment by wintersteiger** [comment]
This looks perfect to me, you got all the relevant bits I think. The CI build failure is unrelated as far as I can tell, I'll try to schedule a re-run.

**Review by vtikoo — APPROVED** [review]
LGTM. Does this mean we no longer intercept SYS_clock_getres?

**Comment by SeanTAllen** [comment]
sgx-lkl-musl portion has been merged. i bumped the submodule here. once it passes CI, I will squash and merge.

**Pull request closed without merging**
