### PR TITLE
README.md: mention SGXLKL_TRACE_LKL_SYSCALL

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by prp** [comment]
Can you try now?

**Comment by Mic92** [comment]
Thanks!

**Comment by Mic92** [comment]
https://github.com/lsds/sgx-lkl/wiki/Building-images-with-nix

**Comment by Mic92** [comment]
Basinga! Also got it working w.r.t pie binaries.

**Comment by Mic92** [comment]
Btw. How are syscalls implemented? Does a syscall in the application running in sgx-lkl always trigger an enclave leave?

**Comment by prp** [comment]
No, host calls are exitless. There is a shared queue between the enclave and the outside.

**Comment by cpriebe** [comment]
Thanks!

I think descriptions of non-critical individual SGX-LKL parameters like `SGXLKL_TRACE_SYSCALL` should also go into the wiki. Ideally we have one page on debugging SGX-LKL enclaves. We can reference the corresponding wiki page in the main README. There are quite a few parameters and we won't be able to discuss all of them there.

**Comment by Mic92** [comment]
Moved that to the wiki:

https://github.com/lsds/sgx-lkl/wiki/Debugging

and only left a link in the README.

**Comment by cpriebe** [comment]
Thanks!

**Pull request merged**
