### PR TITLE
Extend sgx-lkl-cfg to add optional fields with defaults

### PR DESCRIPTION
**Pull request by letmaik**
Sample output:
```
$ tools/sgx-lkl-cfg add-optional --app-cfg tests/containers/cc/app-config.json
Adding optional fields in tests/containers/cc/app-config.json

Added $.cwd: "/"
Added $.exit_status: "full"
Added $.disk_config[0].overlay: false
Added $.disk_config[0].create: false
```

The field notation is JSONPath.

I also added a `--with-optional` flag to the `sgx-lkl-cfg create` command for convenience.

### CODE REVIEW

**Comment by prp** [comment]
I'm not sure that "add optional" is the right terminology here. Isn't this making the enclave_config "complete" by adding all fields (and setting them to defaults)? The tool would output this as a non-canonical version of the enclave_config, and a user would then edit some of the values, right?

**Comment by letmaik** [comment]
Yes, I wasn't sure about the right word. Please suggest an alternative! :)

**Comment by prp** [comment]
`--complete` and `make-complete`?

**Comment by letmaik** [comment]
I'm fine with that, I'll wait a bit and see if anyone objects and whether I still like it in the afternoon...

**Comment by letmaik** [comment]
I changed it to "complete", ready for review. I also fixed a minor schema issue.

**Review by prp — APPROVED** [review]
LGTM

**Pull request merged**
