### PR TITLE
Point LKL submodule to lsds:lkl/upstream-refactor

### PR DESCRIPTION
**Pull request by vtikoo**
### Summary
After merging the corresponding lkl PR, I merged PR #722  without updating the lkl submodule commit.

### CODE REVIEW

**Comment by hukoyu** [comment]
@vtikoo  am I reading wrong? PR title says LKL submodule but link is LTP. Is it a typo?

**Comment by vtikoo** [comment]
Oops..thanks for catching that @hukoyu 👍

**Review by SeanTAllen — APPROVED** [review]

**Comment by SeanTAllen** [comment]
@vtikoo there's no files showing up in the PR. not sure what is going on, I approved as I assume there's an explanation for that.

**Comment by vtikoo** [comment]
@SeanTAllen there is a single commit diff between the lkl submodule commit in sgx-lkl `oe_port` and lkl `upstream-refactor`. That commit is the PR merge commit for lkl PR#5, so there are no files changed.

LKL submodule commit in sgx-lkl `oe_port` - https://github.com/lsds/lkl/commit/385f721b339fe48b188b4924c2663e1ea2cdeb13
PR merge commit and `lsds/lkl:upstream-refactor` HEAD - https://github.com/lsds/lkl/commit/390b2fc5cd8c2e366710969675af4f5c9756e4da

**Review by paulcallen — APPROVED** [review]

**Pull request merged**
