### PR TITLE
Fix memory management for cloned threads.

### PR DESCRIPTION
**Pull request by davidchisnall**
Most of this fix is in the LKL changes but now that LKL is calling join
on the resulting threads, we need to not detach them.

### CODE REVIEW

**Comment by davidchisnall** [comment]
Note: This points to the pre-merge LKL branch, I will update it to point to the merged version once the merge is done.

**Comment by prp** [comment]
It's worth adding @vtikoo's clone-in-a-loop test here and see the CI output.

**Comment by davidchisnall** [comment]
I am basically in meetings until the end of the day and then off until Monday, but I'm happy for someone else to add things to this to the branch.

**Comment by prp** [comment]
@vtikoo could you add your clone-in-a-loop test as a second test under `tests/basic/clone` here? Thanks.

**Review by SeanTAllen — APPROVED** [review]

**Comment by SeanTAllen** [comment]
@prp @vtikoo can we do as a different clone test rather than replacing the existing?

**Comment by prp** [comment]
Yes, that's what I mean. We can have the one Makefile under `tests/basic/clone` run the two different tests in sequence. We have done the same for other test directories.

**Comment by vtikoo** [comment]
@prp could you provide a reference to such a test setup?

**Comment by prp** [comment]
> @prp could you provide a reference to such a test setup?

@vtikoo you can find an example [here](https://github.com/lsds/sgx-lkl/blob/oe_port/tests/basic/exit/Makefile). Actually, this is not particularly clean, and it would be great if you could use a more scalable template for multiple tests. (In this example, tests aren't separate Makefile targets, and the naming isn't applied consistently.)

**Comment by davidchisnall** [comment]
The current clone test will need removing at some point because it assumes it's safe to call libc functions in threads that have not done any libc setup (including `syscall`, which tries to write to `errno` on return, which causes breakage with Vikas' branch), so I don't mind just replacing it with the other test and then merging the relayering work, which then makes all of the pthread tests into clone tests.

**Comment by vtikoo** [comment]
The core issue with clone test is that it doesn't set up its TLS/TP as `pthread_create` would. This causes the errno and strerror failures.
However there seems to be value to keep it around from a debugging perspective, as its without any libc interactions.

**Review by vtikoo — APPROVED** [review]

**Review by prp — APPROVED** [review]
LGTM

**Pull request merged**
