### PR TITLE
Remove unused VDSO clock code

### LINKED ISSUE #188: Remove legacy VDSO code
Now that time handling in SGX-LKL has been replaced, there is legacy VDSO code that should be removed, e.g.:
- https://github.com/lsds/sgx-lkl/blob/a4fc0cc6fea39f30d33783e55626afbff3c7a871/src/main/sgxlkl_run.c#L758 
- https://github.com/lsds/sgx-lkl/blob/5bb8a20a9567e7c2a77bf64957201704a3ca0545/src/main-oe/sgxlkl_params.c#L89
- etc.

All other references to `SGXLKL_GETTIME_VDSO` should also be removed (e.g. as part of the `tests/` and `samples/`).

### PR DESCRIPTION
**Pull request by SeanTAllen**
The VSDO clock code is no longer needed as we now have an in-enclave source
of time.

Closes #188

### CODE REVIEW

**Review by prp — APPROVED** [review]
LGTM, thanks. I presume that you searched for all instances of this across the whole codebase?

Are the CI failures unrelated?

**Comment by SeanTAllen** [comment]
@prp I did search. One CI failure is a known umount issue. The fcntl34 test I am unable to reproduce locally but am not 100% sure I am attempting to recreate it correctly.

**Comment by SeanTAllen** [comment]
@prp as far as i know the failures are unrelated

**Comment by SeanTAllen** [comment]
@prp I dont see how the ltp fcntl/fctl34 test could be related. Especially when it passes locally every time I run it (again, assuming I'm doing it correctly), but I am willing to entertain that it is related.

**Comment by prp** [comment]
As you say, it’s probably unrelated.

**Comment by SeanTAllen** [comment]
I can again with no changes @prp and it passed. We seem to have a flaky test problem now. So every time locally it passed. 1 of (3 or 4) times in CI. Doesn't inspire confidence in the CI.

**Pull request merged**
