### PR TITLE
Update OE for rebase

### PR DESCRIPTION
**Pull request by jhand2**

### CODE REVIEW

**Review by jxyang — APPROVED** [review]

**Review by davidchisnall — APPROVED** [review]

**Comment by jhand2** [comment]
I ran about 5 tests in sw and hw mode. I am not able to repro these failures on an SGX ACC VM. Not sure if anyone has any insights into what could be causing the failures in CI

**Comment by prp** [comment]
Hmm, we should have a good CI run before this gets merged. It seems that it segfaults during enclave creation. Are we sure that the CI run has clean trees?

**Comment by jxyang** [comment]
@prp I am looking at the pipeline failures. But running into a build error on oe_port:
```
CC main-oe/sgxlkl_run_oe.c
main-oe/sgxlkl_run_oe.c:49:10: fatal error: host/sgxlkl_u.h: No such file or directory
 #include "host/sgxlkl_u.h"
```
Did anyone run into the same problem?

**Comment by jhand2** [comment]
> @prp I am looking at the pipeline failures. But running into a build error on oe_port:
> 
> ```
> CC main-oe/sgxlkl_run_oe.c
> main-oe/sgxlkl_run_oe.c:49:10: fatal error: host/sgxlkl_u.h: No such file or directory
>  #include "host/sgxlkl_u.h"
> ```
> 
> Did anyone run into the same problem?

I had to delete the `openeenclave/build` directory and do a clean build. I guess sgx-lkl's `make clean` doesn't already do that.

**Comment by prp** [comment]
> > @prp I am looking at the pipeline failures. But running into a build error on oe_port:
> > ```
> > CC main-oe/sgxlkl_run_oe.c
> > main-oe/sgxlkl_run_oe.c:49:10: fatal error: host/sgxlkl_u.h: No such file or directory
> >  #include "host/sgxlkl_u.h"
> > ```
> > 
> > 
> > Did anyone run into the same problem?
> 
> I had to delete the `openeenclave/build` directory and do a clean build. I guess sgx-lkl's `make clean` doesn't already do that.

`make distclean` should rebuild OE, and I believe that the CI pipeline already uses this. Also, we are doing a fresh clone for a CI run (right?), so the checked out tree should also be clean.

**Comment by jxyang** [comment]
Rebase to the latest oe_port

**Comment by jxyang** [comment]
The tests crash in sw mode on pipeline VMs, 100% repro. However, I can't repro the crash on my local VMs, with or without SGX capability, making it challenging to debug.

I added some debug messages to the `sgxlkl_run_oe.c`.  Running it on pipeline VMs indicates the crash happens during `oe_create_enclave`.

I need help on how to clone a pipeline VM, @letmaik ?

**Comment by letmaik** [comment]
Can you repro with the package built in CI? https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1644&view=artifacts&type=publishedArtifacts

**Comment by jxyang** [comment]
@letmaik I Installed SGX-LKL with the debian package, and the tests passed as well. I am completely out of clue why these tests only fail on pipeline VMs.

Do we have the capability of cloning pipeline VMs, like OE does, by providing a gallery image to `az vm create`? e.g, `/subscriptions/c4fdda6e-bfbd-4b8e-9703-037b3a45bf37/resourceGroups/OE-Jenkins-Images/providers/Microsoft.Compute/galleries/Production_Images/images/ubuntu-18.04/versions/latest`

**Comment by letmaik** [comment]
@jxyang The script https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/create_vmss.sh is used to create the scale set pools. As you can see it's based on a stock image (Canonical:UbuntuServer:18_04-lts-gen2:latest). Nothing special is done to that image, just the usual apt get etc https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/install_prerequisites.sh.
The easiest way to debug this is to look at the output of the gdb test https://github.com/lsds/sgx-lkl/blob/oe_port/tests/tools/sgx-lkl-gdb/Makefile as this runs gdb in batch mode and dumps a stack trace. I'll copy it here for convenience:

```
[   SGX-LKL  ] oe_create_enclave...
[   SGX-LKL  ] Enclave config: {"args":["helloworld"],"clock_res":[{"resolution":"0000000000000001"},{"resolution":"0000000000000001"},{"resolution":"0000000000000000"},{"resolution":"0000000000000000"},{"resolution":"0000000000000001"},{"resolution":"00000000003d0900"},{"resolution":"00000000003d0900"},{"resolution":"0000000000000001"}],"cwd":"/","env":[],"esleep":"16000","espins":"500","ethreads":"8","exit_status":"full","format_version":"1","fsgsbase":false,"host_import_env":[],"hostname":"lkl","hostnet":false,"image_sizes":{"num_heap_pages":"262144","num_stack_pages":"1024"},"io":{"block":true,"console":true,"network":true},"kernel_cmd":"mem=32M","kernel_verbose":true,"max_user_threads":"256","mmap_files":"shared","mode":"sw_debug","mounts":[],"net_gw4":"10.0.1.254","net_ip4":"10.0.1.1","net_mask4":"24","oe_heap_pagecount":"8192","root":{"key":"","key_id":null,"overlay":false,"readonly":false,"roothash":null,"roothash_offset":"0"},"stacksize":"524288","swiotlb":true,"sysctl":null,"tap_mtu":"0","verbose":true,"wg":{"ip":"10.0.2.1","key":null,"listen_port":"56002","peers":[]}}
oegdb: Enclave /opt/sgx-lkl-debug/lib/libsgxlkl.so.signed loaded in simulation mode
oegdb: Symbols loaded for enclave 

oegdb: All tcs set to debug for enclave 


Program received signal SIGSEGV, Segmentation fault.
oe_enter () at /agent/_work/2/s/openenclave/enclave/core/sgx/enter.S:181
181	    oe_cleanup_xstates
#0  oe_enter () at /agent/_work/2/s/openenclave/enclave/core/sgx/enter.S:181
#1  0x0000000040085760 in oe_enter_sim (tcs=0x7fe040f49000, aep=<optimized out>, arg1=281479271677952, arg2=1076503504, arg3=0x7fffffffb9a8, arg4=0x7fffffffb9a0, enclave=0x402a23d0) at /agent/_work/2/s/openenclave/host/sgx/enter.c:267
#2  0x000000004007677e in _enter_sim (enclave=0x402a23d0, tcs_=0x7fe040f49000, aep=1074287088, arg1=281479271677952, arg2=1076503504, arg3=0x7fffffffb9a8, arg4=0x7fffffffb9a0) at /agent/_work/2/s/openenclave/host/sgx/calls.c:124
#3  0x00000000400750ab in _do_eenter (enclave=0x402a23d0, tcs=0x7fe040f49000, aep=1074287088, code_in=OE_CODE_ECALL, func_in=1, arg_in=1076503504, code_out=0x7fffffffb99c, func_out=0x7fffffffb99a, result_out=0x7fffffffb998, arg_out=0x7fffffffb990) at /agent/_work/2/s/openenclave/host/sgx/calls.c:189
#4  oe_ecall (enclave=0x402a23d0, func=1, arg=1076503504, arg_out_ptr=0x7fffffffbb10) at /agent/_work/2/s/openenclave/host/sgx/calls.c:627
#5  0x0000000040036c12 in _initialize_enclave (enclave=0x402a23d0) at /agent/_work/2/s/openenclave/host/sgx/create.c:436
#6  0x0000000040036661 in oe_create_enclave (enclave_path=0x7fffffffc240 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", enclave_type=OE_ENCLAVE_TYPE_SGX, flags=3, settings=0x7fffffffc050, setting_count=1, ocall_table=0x4029ba20 <__sgxlkl_ocall_function_table>, ocall_count=17, enclave_out=0x7fffffffc0f8) at /agent/_work/2/s/openenclave/host/sgx/create.c:1013
#7  0x0000000040020343 in oe_create_sgxlkl_enclave (path=0x7fffffffc240 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", type=OE_ENCLAVE_TYPE_SGX, flags=3, settings=0x7fffffffc050, setting_count=1, enclave=0x7fffffffc0f8) at main-oe/sgxlkl_u.c:1946
#8  0x000000004000f944 in _create_enclave (libsgxlkl=0x7fffffffc240 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", oe_flags=3, oe_enclave=0x7fffffffc0f8) at main-oe/sgxlkl_run_oe.c:1374
#9  0x0000000040010d47 in main (argc=1, argv=0x7fffffffd380, envp=0x7fffffffd390) at main-oe/sgxlkl_run_oe.c:1877
Makefile:46: recipe for target 'run-sw' failed
make: *** [run-sw] Error 1
make run-sw: FAILED WITH EXIT CODE: 2
Test run completed with EXIT CODE 2
```

**Comment by jxyang** [comment]
Thanks @letmaik . Very helpful suggestions.

**Comment by jxyang** [comment]
We have root caused the issue and this PR is blocked by https://github.com/openenclave/openenclave/issues/3350

**Pull request merged**
