### PR TITLE
LTP: Use https://github.com/lsds/ltp/sgx-lkl instead of patches

### PR DESCRIPTION
**Pull request by hukoyu**
We created LTP fork https://github.com/lsds/ltp
Our LTP test patches were based on tag 20190930. Created branch sgx-lkl from tag20190930 that our patches valid for, and applied all existing patches to this LTP fork sgx-lkl branch.

Before to run LTP tests we were downloading LTP from https://github.com/linux-test-project/ltp.git (tag: 20190930) and applying all of our patches and then building. Now we will have these changes done on this LTP fork on sgx-lkl branch and it will be downloaded and built directly.

We don't need to apply patches anymore.  https://github.com/lsds/ltp/sgx-lkl will have the necessary code changes. 

To make necessary code changes to enable an LTP test for sgx-lkl, a PR will be submitted to https://github.com/lsds/ltp/sgx-lkl and it will be reviewed and merged. 

Then new test must be enabled in test/ltp/ltp-batch1/ltp_disabled_tests.txt or test/ltp/ltp-batch1/ltp_disabled_tests.txt

### CODE REVIEW

**Comment by hukoyu** [comment]
Pipeline run passed https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_build/results?buildId=1522&view=results

**Review by davidchisnall — APPROVED** [review]
Thanks for doing this!

**Comment by davidchisnall** [comment]
CI doesn't seem to have run on this PR.  I'd like to see a successful CI run before it's merged but I don't understand why it did not run automatically.

Edit: I missed the comment saying that CI had run.  Looks fine.  Any ideas why it's not reporting the CI result in the pre-merge checks bit below?

**Comment by SeanTAllen** [comment]
This looks good. I have a question related to lsds/LTP. None of the commits I looked at have a reason for the change. Where do we go in the future to look to understand why a patch was made? Will that be in the commit comments going forward? Are we recording that in a file in the lsds/LTP repo? I missed the conversation on how that will be occurring. I don't have any particular preference as long as ideally...

1) its part of the lsds/LTP repo.
2) the reason is findable along with the change as part of the commit (be it in the commit comment or as part of an update to a file that goes along with the change).

**Pull request merged**
