### PR TITLE
Ken/issue297

### LINKED ISSUE #297: [Tests] lkl_access_ok() should return failure on test invalid access, not fatal exit.
LTP tests expects EFAULT error returned when trying to access an invalid address. 
sgx-lkl doesn't return EFAULT but ABORTs.

Sample LTP tests:
https://github.com/lsds/sgx-lkl/pull/550
listxattr01,02 

```
2020-05-22T08:36:47.954418Z [(H)ERROR] tid(0x7f682a12e700) | :OE_ENCLAVE_ABORTING [/home/prashant/openenclave/host/calls.c:oe_call_enclave_function_by_table_id:91]
[   SGX-LKL  ] ethread (1: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=1 result=19 (OE_ENCLAVE_ABORTING))
```

in umount02 when it test umount with null, it causes enclave to abort. Normally application is expected to get EFAULT. But the back trace is showing that in lkl it calls oe_abort when address is invalid.
```
#0 lkl_access_ok (addr=0, size=1) at lkl/setup.c:1499
#1 0x00007fff0010aaff in __lkl_access_ok (size=, addr=) at ./arch/lkl/include/asm/uaccess.h:14
#2 strncpy_from_user (count=, src=, dst=) at ./include/asm-generic/uaccess.h:233
#3 getname_flags (filename=0x0, flags=0, empty=0x0) at fs/namei.c:149
#4 0x00007fff0010ad2d in getname (filename=) at fs/namei.c:209
#5 0x00007fff0010da1d in user_path_mountpoint_at (dfd=0, name=, flags=1049890816, path=0x7fff3e941020)
at fs/namei.c:2745
#6 0x00007fff0012003d in ksys_umount (name=0x7fff3e941000 " \020\224>\377\177", flags=0) at fs/namespace.c:1680
#7 0x00007fff00120479 in __do_sys_umount (flags=, name=) at fs/namespace.c:1706
#8 __se_sys_umount (name=, flags=) at fs/namespace.c:1704
#9 0x00007fff00088076 in run_syscall (params=, no=) at arch/lkl/kernel/syscalls.c:44
#10 lkl_syscall (no=140734243278880, params=0x0) at arch/lkl/kernel/syscalls.c:183
#11 0x00007fff0054901a in __filter_syscall2 (n=39, a1=0, a2=0) at ./src/internal/syscall.h:161
#12 0x00007fff0054924a in umount (special=0x0) at src/linux/mount.c:11```
if (!ret)
{
sgxlkl_fail("lkl_access_check failed: %p\n", (void*)addr);
}
return ret;
```
Currently sgx behaviour is to call enclave ABORT, if address is not within enclave address range. Because of this test program
is causing enclave abort and exiting with non-zero exit code.

### PR DESCRIPTION
**Pull request by KenGordon**
Fix for issue 297. This was caused by the code that checks for bad memory addresses exiting with a fatal error rather than just logging as appropriate and telling the caller that the memory is not valid.

One line fix as suggested by David.

The complication was turning on and properly reverting all the tests in ltp which would trigger the bug.  The commits were not entirely clear of other changes.
[Test] system calls with NULL causes abort #169 is a duplicate of 297. Some cases were labelled with TODOs for that one.
See the LTP PR to match is https://github.com/lsds/ltp/pull/51 against branch ken/issue297ltp

### CODE REVIEW

**Review by hukoyu — APPROVED** [review]
LGTM

**Comment by hukoyu** [comment]
@KenGordon  @SeanTAllen  a question here. In this PR we are bumping LTP submodule commit. But these files are part of lsds/ltp PR https://github.com/lsds/ltp/pull/51 which is not merged yet. So how this works? Should we merge https://github.com/lsds/ltp/pull/51 first and then update the ltp submodule here and then merge this PR? Or it doesn't matter https://github.com/lsds/ltp/pull/51 is merged or not and this ltp submodule bump is good enough?

**Comment by SeanTAllen** [comment]
@hukoyu this will need to be rebased manually first. generally the workflow is to merged the corresponding submodule commit and then merge the sgx-lkl commit.

if no squashing was involved for the submodule commit this works fine. if the submodule commit involves squashing then the PR commit first needs to be updated to the squashed commit for the submodule.

**Comment by davidchisnall** [comment]
@SeanTAllen: Minor correction, GitHub never does fast-forward merges (even if you say rebase) because it adds PR metadata to the final version of the commit.  This means that the commit hash will always be different.  The two workflows that work are:

 - Merge the submodule commit, then update the PR to include the new hash and merge that.
 - Merge this pointing at its current git hash then make sure that those changes are in the submodule head so that the next submodule update will pull them in as long as it's based on the current main branch.

Neither is particularly great.

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
@KenGordon, please fix the conflicts and then do the merge dance outlined above.

**Pull request merged**
