### PR TITLE
Update to latest ltp tests on sgx-lkl branch of ltp

### PR DESCRIPTION
**Pull request by SeanTAllen**
When updates to ltp where made, they were unaware that corresponding
PRs had to be done to sgx-lkl to update. This will pull in the
latest changes (assuming this passes CI)

### CODE REVIEW

**Review by prp — APPROVED** [review]
LGTM. Let's see if the CI passes, as we should again get into the habit of having clean CI runs :-)

**Comment by SeanTAllen** [comment]
@prp have we been merging without clean runs?

**Comment by prp** [comment]
Well, people merge when they think that certain CI failures are unrelated.

**Comment by wintersteiger** [comment]
Was there a separate PR in the LTP repo (with reviews) and this is intended to be only the bump to the new commit? 

I agree, it would be nice if we could get to a state where CI success is a hard requirement!

**Review by hukoyu — APPROVED** [review]
@SeanTAllen  I just merged one more PR on lsds/ltp. if you can get it as well it will be nice.

**Comment by SeanTAllen** [comment]
@hukoyu I'll get in another PR.

**Comment by SeanTAllen** [comment]
@wintersteiger yes, I explained to @hukoyu and he can pass along to folks working on ltp repo how to work with the submodule so that the tests go through CI. They were unaware and only testing locally. Going forward that should happen.

@hukoyu I'll open a PR for the latest change that was merged. Anything else should go through the process I explained to you outside of GitHub before being merged to the sgx-lkl branch in the ltp repo.

**Pull request merged**
