### PR TITLE
Update OE submodule

### PR DESCRIPTION
**Pull request by jhand2**
OE submodule branch was rebased against latest master on June 22, 2020

### CODE REVIEW

**Comment by wintersteiger** [comment]
I think this doesn't include https://github.com/openenclave/openenclave/commit/f7bdf8069da972acf4b6828d7e022ba0d96e66f6 yet (merged just now), could you include that one too?

**Comment by hukoyu** [comment]
@jhand2  LTP tests are failing with this PR

```
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (65e7ec9) LKL 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW    ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... timeout: the monitored command dumped core
TEST_FAILED EXIT CODE: 134
```

cc @wintersteiger

**Comment by wintersteiger** [comment]
@jhand2 while you're at it, could you rebase again to include https://github.com/openenclave/openenclave/pull/3166? It's hard to figure out what's included from the github interface, sorry if that's already in there and also sorry it's a busy day today :-) 

No idea what's going on with the LTP tests yet.

**Comment by hukoyu** [comment]
With this PR all hw tests are failing and only sw tests are passing.
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_build/results?buildId=894&view=results

@jhand2 @wintersteiger merging this PR will break a lot of things. It is 100% repro. @wintersteiger  
debugging one of failing hw tests can help figure out the issue. I think all of these tests are failing due to same regression.

cc @jxyang @paulcallen @Pengpeng-Microsoft @davidchisnall @prp @letmaik @mikbras

**Review by hukoyu — CHANGES_REQUESTED** [review]
With this PR all hw tests are failing and only sw tests are passing.
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_build/results?buildId=894&view=results

@jhand2 @wintersteiger merging this PR will break a lot of things. It is 100% repro. @wintersteiger
debugging one of failing hw tests can help figure out the issue. I think all of these tests are failing due to same regression.

**Comment by jhand2** [comment]
unable to repro. I spot-checked 10 or so tests on my VM and they all passed.

**Comment by wintersteiger** [comment]
@hukoyu why do those tests fail? What does error code 134 mean? Can you get us a stack trace that shows us where the segfault occurs (if it is one)? It's obviously not a 100% report if @jhand2 can't reproduce it, so I'll give it a try later today.

**Comment by wintersteiger** [comment]
Some of the normal tests also failed in that particular CI run. I just tried 10 of them and they all pass locally without any problems. @hukoyu can you make sure that there's no leftover state left on the CI machines so that OE is built cleanly from scratch, without keep object files from previous runs, etc?

**Comment by hukoyu** [comment]
I also run tests and they are passing locally for me as well. Then issue is tests are failing for almost all  hw tests (ltp and non-ltp) in CI Pipeline. If we merge this PR, pipeline will fail for sure. We need to understand why tests are failing for hw in pipeline. @letmaik is the expert and author of pipeline and he has the most context. @letmaik in this PR OE submodule is being updated and with this PR most of the HW tests are failing in pipeline but we cannot repro localy. We need your insight here to understand reason for these failures in CI pipeline. 
cc @jhand2 @wintersteiger @prp @davidchisnall @paulcallen @jxyang @Pengpeng-Microsoft

**Comment by letmaik** [comment]
I'm not sure what the issue is. It seems related to the OE update though. 

Things to try:
- Since the abort is happening in OE code, it may be useful to enable verbose logging with `export OE_LOG_LEVEL=VERBOSE` before running tests.
- If that doesn't help, then I would change the run-hw target of a single test case to run under gdb with sgx-lkl-gdb. Something like `sgx-lkl-gdb -batch -ex "handle SIGILL nostop noprint" -ex run -ex bt --args sgx-lkl-run-oe ...`.

Things to fix:
- In fact all hw tests are failing. The ones that are not failing are false positives. In particular the basic/illegal_instructions test has to be fixed as it simply "inverts" the exit code.
- Printing host-side stack traces would help, if anyone can take https://github.com/lsds/sgx-lkl/issues/205 then error diagnosis would be easier in the future.

**Comment by jhand2** [comment]
No matter what I do I can't make it fail locally.

Maybe it has to do with the machine configuration in CI? How are the machines configured? (SGX driver version, PSW/DCAP versions, etc).

**Comment by letmaik** [comment]
The "Things to try" were meant to be run in CI. @hukoyu Could you do some experiments?

**Comment by wintersteiger** [comment]
@letmaik is there a way for me to log in to the CI machine so I can run the tests manually?

**Comment by letmaik** [comment]
> @letmaik is there a way for me to log in to the CI machine so I can run the tests manually?

Since this is a scale set, all the VMs are behind an internal subnet. I've asked the pipelines folks for advice on how to access individual VMs publically.

In the meantime, I've created a branch to run helloworld under gdb in CI. Let's see what that brings: https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=928&view=results

**Comment by wintersteiger** [comment]
`/opt/sgx-lkl-debug/bin/sgx-lkl-gdb: line 47: gdb: command not found` :-(

**Comment by letmaik** [comment]
```
2020-06-24T11:40:28.2819939Z 0x00007ffff6cffe97 in raise () from /opt/sgx-lkl-debug/bin/../lib/external/libc.so.6
2020-06-24T11:40:28.2820428Z #0  0x00007ffff6cffe97 in raise () from /opt/sgx-lkl-debug/bin/../lib/external/libc.so.6
2020-06-24T11:40:28.2820897Z #1  0x00007ffff6d01801 in abort () from /opt/sgx-lkl-debug/bin/../lib/external/libc.so.6
2020-06-24T11:40:28.2821251Z #2  0x000000004008f565 in _load_sgx_enclave_common_impl () at /agent/_work/1/s/openenclave/host/sgx/sgx_enclave_common_wrapper.c:138
2020-06-24T11:40:28.2821724Z #3  0x00007ffff70c1827 in __pthread_once_slow (once_control=0x402b1b00 <_load_sgx_enclave_common._once>, init_routine=0x4008ec60 <_load_sgx_enclave_common_impl>) at pthread_once.c:116
2020-06-24T11:40:28.2822222Z #4  0x000000004004bea6 in oe_once (once=0x402b1b00 <_load_sgx_enclave_common._once>, func=0x4008ec60 <_load_sgx_enclave_common_impl>) at /agent/_work/1/s/openenclave/host/linux/hostthread.c:46
2020-06-24T11:40:28.2822716Z #5  0x000000004008ea44 in _load_sgx_enclave_common () at /agent/_work/1/s/openenclave/host/sgx/sgx_enclave_common_wrapper.c:145
2020-06-24T11:40:28.2823224Z #6  0x000000004008e996 in oe_sgx_enclave_create (base_address=0x0, virtual_size=2147483648, initial_commit=1119490048, type=1, info=0x402b7000, info_size=4096, enclave_error=0x7fffffffb034) at /agent/_work/1/s/openenclave/host/sgx/sgx_enclave_common_wrapper.c:158
2020-06-24T11:40:28.2823799Z #7  0x00000000400269e8 in oe_sgx_create_enclave (context=0x7fffffffc0a8, enclave_size=2147483648, enclave_commit_size=1119490048, enclave_addr=0x7fffffffb5a0) at /agent/_work/1/s/openenclave/host/sgx/sgxload.c:467
2020-06-24T11:40:28.2824584Z #8  0x00000000400199bb in oe_sgx_build_enclave (context=0x7fffffffc0a8, path=0x7fffffffc590 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", properties=0x0, enclave=0x402b25c0) at /agent/_work/1/s/openenclave/host/sgx/create.c:816
2020-06-24T11:40:28.2825552Z #9  0x000000004001b4e5 in oe_create_enclave (enclave_path=0x7fffffffc590 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", enclave_type=OE_ENCLAVE_TYPE_SGX, flags=1, settings=0x0, setting_count=0, ocall_table=0x402aca80 <__sgxlkl_ocall_function_table>, ocall_count=8, enclave_out=0x7fffffffc248) at /agent/_work/1/s/openenclave/host/sgx/create.c:965
2020-06-24T11:40:28.2826541Z #10 0x00000000400176b1 in oe_create_sgxlkl_enclave (path=0x7fffffffc590 "/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed", type=OE_ENCLAVE_TYPE_SGX, flags=1, settings=0x0, setting_count=0, enclave=0x7fffffffc248) at main-oe/sgxlkl_u.c:633
2020-06-24T11:40:28.2827190Z #11 0x0000000040011480 in main (argc=4, argv=0x7fffffffd6b8, envp=0x7fffffffd6e0) at main-oe/sgxlkl_run_oe.c:1811
```

**Comment by letmaik** [comment]
OK I know what it is. It's caused by OE's recent change in linking of Intel SGX libraries. They are dlopen'd now, which means they are not automatically picked up anymore during creation of the standalone Debian package. I'll fix it...

**Comment by wintersteiger** [comment]
Awesome, thanks!

**Comment by letmaik** [comment]
There was actually an error message from OE regarding this but it was swallowed due to #520:
```
2020-06-24T13:24:34.000000Z [(H)ERROR] tid(0x7f4fd08b0740) | Failed to load libsgx_enclave_common.so
 [/.../git/sgx-lkl-oe/openenclave/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:128]
2020-06-24T13:24:34.000000Z [(H)ERROR] tid(0x7f4fd08b0740) | Terminating host application. [/.../git/sgx-lkl-oe/openenclave/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:137]
```

I'm waiting for CI to succeed and then @jhand2 can merge my changes from [`letmaik/update_oe_ci_debug`](https://github.com/lsds/sgx-lkl/compare/oe_port...letmaik/update_oe_ci_debug).

**Comment by wintersteiger** [comment]
Sounds good, thanks! 

`OE_LOG_LEVEL=VERBOSE` is super verbose as it dumps a line for every heap/stack page that's being measured which we really don't need to see, I think `OE_LOG_LEVEL=INFO` would be enough.

**Comment by letmaik** [comment]
> `OE_LOG_LEVEL=VERBOSE` is super verbose as it dumps a line for every heap/stack page that's being measured which we really don't need to see, I think `OE_LOG_LEVEL=INFO` would be enough.

Let's leave it at ERROR (the default), as INFO also turns on logging for the Azure DCAP Client which is quite verbose.

**Review by letmaik — APPROVED** [review]

**Comment by letmaik** [comment]
@hukoyu This is passing now, can you approve?

**Review by wintersteiger — APPROVED** [review]
LGTM!

**Comment by jhand2** [comment]
Thanks @letmaik! I rebased my branch against oe_port.

I didn't realized SGX-LKL ran without dependencies on system lib paths in CI. Is that the recommended scenario that users/developers follow, or just how it is run in CI?

**Comment by letmaik** [comment]
@jhand2 The point of it is that it can be directly mounted into a Docker container (so that SGX-LKL doesn't have to be bundled with each image). It's also what users will get via the Debian package, and hence what's tested in CI.

**Review by hukoyu — APPROVED** [review]
Thanks @letmaik finding root cause and fixing this. @jhand2 looks good now.

**Comment by wintersteiger** [comment]
The tests are still failing. @jhand2 I think @letmaik s changes weren't in oe_port yet, could you merge them into this PR?

**Comment by jhand2** [comment]
> The tests are still failing. @jhand2 I think @letmaik s changes weren't in oe_port yet, could you merge them into this PR?

I see the following in my branch

```
commit 27e70e13bf61c9bb317712b062c18d840cb1d483 (origin/oe_port, oe_port)
Author: Maik Riechert <maik.riechert@microsoft.com>
Date:   Wed Jun 24 15:40:39 2020 +0100

    fail on pipe failures in make_self_contained.sh (#521)
```

**Comment by wintersteiger** [comment]
That's related, but not the same. I think the critical bit are the two `.so`s in the libs list here: https://github.com/lsds/sgx-lkl/compare/oe_port...letmaik/update_oe_ci_debug

**Comment by letmaik** [comment]
@jhand2 I already pushed the fix to your branch earlier but you got rid of it again :)

**Comment by jhand2** [comment]
> @jhand2 I already pushed the fix to your branch earlier but you got rid of it again :)

oh :smile: I rebased against oe_port without pulling and then force pushed

**Comment by hukoyu** [comment]
@jhand2 is there blocking issue merging this PR? I thought @letmaik fixed the blocking issue.

**Comment by jhand2** [comment]
Just re-added @letmaik's change. Should be good to merge once tests pass

**Pull request merged**
